SELECT nombre FROM tienda.producto;
SELECT nombre, precio FROM tienda.producto;
SELECT * FROM tienda.producto;
SELECT nombre, precio, (round(precio * 0.99,2)) as precioUSD FROM tienda.producto;
SELECT nombre AS 'nom_de_producto' , precio AS 'euros', (round(precio * 0.99,2)) AS 'dòlars' FROM tienda.producto;
SELECT UPPER(nombre), precio FROM tienda.producto;
SELECT LOWER(nombre), precio FROM tienda.producto;
SELECT nombre, left(UPPER(nombre),2) as Upper2char FROM tienda.fabricante;
SELECT nombre, round(precio) FROM tienda.producto;
SELECT nombre, TRUNCATE(precio,0) FROM tienda.producto;
SELECT fabricante.codigo FROM tienda.fabricante INNER JOIN tienda.producto ON tienda.fabricante.codigo = tienda.producto.codigo_fabricante;
SELECT DISTINCT fabricante.codigo FROM tienda.fabricante INNER JOIN tienda.producto ON tienda.fabricante.codigo = tienda.producto.codigo_fabricante;
SELECT nombre FROM tienda.fabricante ORDER BY  nombre;
SELECT nombre FROM tienda.fabricante ORDER BY  nombre DESC;
SELECT nombre FROM tienda.producto ORDER BY nombre, precio DESC;
SELECT nombre FROM tienda.producto LIMIT 5;
SELECT codigo, nombre FROM tienda.fabricante LIMIT 3,2;
SELECT nombre, precio FROM tienda.producto ORDER BY precio DESC LIMIT 1;
SELECT nombre, precio FROM tienda.producto ORDER BY precio LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT producto.nombre, producto.precio, fabricante.nombre AS nombre_fabricante FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo;
SELECT producto.nombre, producto.precio, fabricante.nombre AS nombre_fabricante FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo ORDER BY fabricante.nombre;
SELECT producto.codigo, producto.nombre, fabricante.codigo, fabricante.nombre FROM tienda.producto RIGHT JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo ORDER BY  producto.precio LIMIT 1;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo ORDER BY  producto.precio DESC LIMIT 1;
SELECT producto.codigo, producto.nombre, producto.precio, fabricante.nombre AS nombre_fabricante FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo WHERE fabricante.nombre = 'Lenovo';
SELECT producto.codigo, producto.nombre, producto.precio, fabricante.nombre AS nombre_fabricante FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo WHERE fabricante.nombre = 'Crucial' AND producto.precio > 200;
SELECT producto.codigo, producto.nombre, producto.precio, fabricante.nombre AS nombre_fabricante FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo WHERE fabricante.nombre = 'Asus' OR fabricante.nombre = 'Hewlett-Packard' OR fabricante.nombre = 'Seagate';
SELECT producto.codigo, producto.nombre, producto.precio, fabricante.nombre AS nombre_fabricante FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo WHERE fabricante.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT producto.nombre, producto.precio, fabricante.nombre AS nombre_fabricante FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo WHERE RIGHT(fabricante.nombre, 1) = 'e';
SELECT producto.nombre, producto.precio, fabricante.nombre AS nombre_fabricante FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo WHERE fabricante.nombre LIKE '%w%';
SELECT producto.nombre, producto.precio, fabricante.nombre AS nombre_fabricante FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo WHERE producto.precio >= 180 ORDER BY producto.precio DESC, producto.nombre;
SELECT DISTINCT fabricante.codigo, fabricante.nombre AS nombre_fabricante FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo;
SELECT fabricante.codigo, fabricante.nombre AS nombre_fabricante, producto.codigo, producto.nombre, producto.precio, producto.codigo_fabricante FROM tienda.fabricante LEFT JOIN tienda.producto ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo;
SELECT fabricante.codigo, fabricante.nombre as nombre_fabricante FROM fabricante WHERE fabricante.codigo NOT IN (SELECT DISTINCT producto.codigo_fabricante FROM producto);
SELECT producto.codigo, producto.nombre, producto.precio, producto.codigo_fabricante FROM producto WHERE producto.codigo_fabricante IN (SELECT fabricante.codigo FROM fabricante WHERE fabricante.nombre = 'Lenovo');
SELECT producto.codigo, producto.nombre, producto.precio, producto.codigo_fabricante FROM producto WHERE producto.precio = ( SELECT producto.precio FROM producto WHERE producto.codigo_fabricante = (SELECT fabricante.codigo FROM fabricante WHERE nombre = 'Lenovo') ORDER BY producto.precio DESC LIMIT 1);  
SELECT producto.nombre FROM producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo WHERE tienda.fabricante.nombre = 'Lenovo' ORDER BY producto.precio DESC LIMIT 1;
SELECT producto.nombre FROM producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo WHERE tienda.fabricante.nombre = 'Hewlett-Packard' ORDER BY producto.precio LIMIT 1;
SELECT producto.codigo, producto.nombre, producto.precio, producto.codigo_fabricante FROM producto WHERE producto.precio >= (SELECT producto.precio FROM producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo WHERE tienda.fabricante.nombre = 'Lenovo' ORDER BY producto.precio DESC LIMIT 1);
SELECT producto.codigo, producto.nombre, producto.precio, producto.codigo_fabricante FROM tienda.producto INNER JOIN tienda.fabricante ON tienda.producto.codigo_fabricante = tienda.fabricante.codigo WHERE tienda.fabricante.nombre = 'Asus' AND producto.precio > (SELECT SUM(producto.precio) / Count(producto.precio) as Media FROM producto);